SHOW DATABASES;
USE STORE;
SHOW TABLES;
## HOW TO SELECT THE PARTICULER DATA FROM THE TABLES ##
SELECT * FROM CUSTOMERS;
## HOW TO SELECT THE PARTICULER COLUMES ##
SELECT PHONE, CITY FROM CUSTOMERS;
## HOW TO ADD NEW COLUMES ##
SELECT STATE, CITY, CITY+100 FROM CUSTOMERS
